<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Query</name>
   <tag></tag>
   <elementGuidId>cd49590d-ed1f-47db-a33e-b17a4a2ae39d</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formid</name>
      <type>Main</type>
      <value>_searchforemployersip_WAR_registrationportlet_fm</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnQueryId</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>url</name>
      <type>Main</type>
      <value>https://assist2-uat.perkeso.gov.my/web/registration/eis-update/form-3-eis-cessation-as-employer?p_auth=NGkK15Vh&amp;p_p_id=searchforemployersip_WAR_registrationportlet&amp;p_p_lifecycle=1&amp;p_p_state=normal&amp;p_p_mode=view&amp;p_p_col_id=column-1&amp;p_p_col_count=1&amp;_searchforemployersip_WAR_registrationportlet_javax.portlet.action=exeAction&amp;_searchforemployersip_WAR_registrationportlet_regActionKey=611&amp;_searchforemployersip_WAR_registrationportlet_cmd=discontinueBusinessSipEmployerInfoSubmitId&amp;_searchforemployersip_WAR_registrationportlet_browserIdKey=1536115006323&amp;_searchforemployersip_WAR_registrationportlet_processInstanceIdKey=&amp;_searchforemployersip_WAR_registrationportlet_regViewKey=88&amp;_searchforemployersip_WAR_registrationportlet_mvcPath=%2Fapps%2Freg%2Fdiscontinue_business_sip%2Fdiscontinue_business_sip_preview.jsp</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-confirmation-title</name>
      <type>Main</type>
      <value>Confirmation</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-confirmation-content</name>
      <type>Main</type>
      <value>Are You Sure To Query?</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>targets</name>
      <type>Main</type>
      <value>baseMsgDivId</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-lg m-t-20 col-md-1 pull-right btnQuery popUpBrowserIdBtn</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> QUERY
					</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnQueryId&quot;)</value>
   </webElementProperties>
</WebElementEntity>
