<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Save  Continue in Under Enforcement Page</name>
   <tag></tag>
   <elementGuidId>945681bf-e3c1-4788-8b7f-166b12e36b3a</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formid</name>
      <type>Main</type>
      <value>_ssn_WAR_registrationportlet_remarkForm</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://assist2-uat.perkeso.gov.my/web/registration/request-ssn?p_auth=o6XGmyxA&amp;p_p_id=ssn_WAR_registrationportlet&amp;p_p_lifecycle=1&amp;p_p_state=normal&amp;p_p_mode=view&amp;_ssn_WAR_registrationportlet_javax.portlet.action=exeAction&amp;_ssn_WAR_registrationportlet_regActionKey=22&amp;_ssn_WAR_registrationportlet_cmd=submitSsnId&amp;_ssn_WAR_registrationportlet_isUnderEnforcementCase=true&amp;_ssn_WAR_registrationportlet_browserIdKey=1535438843100&amp;_ssn_WAR_registrationportlet_processInstanceIdKey=&amp;_ssn_WAR_registrationportlet_regViewKey=52&amp;_ssn_WAR_registrationportlet_mvcPath=%2Fapps%2Freg%2Fssn%2Fssn_preview.jsp</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>targets</name>
      <type>Main</type>
      <value>baseMsgDivId</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-lg blueBtn col-md-2 pull-right browserIdBtn</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> SAVE &amp; CONTINUE	
								</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;yui_patched_v3_11_0_1_1535438879920_467&quot;)/div[@class=&quot;button-holder&quot;]/a[@class=&quot;btn btn-lg blueBtn col-md-2 pull-right browserIdBtn&quot;]</value>
   </webElementProperties>
</WebElementEntity>
