<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Add Document</name>
   <tag></tag>
   <elementGuidId>bd40fa60-2825-4cb5-9f79-86edd86661cb</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_searchforemployer_WAR_registrationportlet_dialogBtn</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formid</name>
      <type>Main</type>
      <value>_searchforemployer_WAR_registrationportlet_saveNContinueFormId</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://assist2-uat.perkeso.gov.my/web/registration/update/update-add-supporting-document?p_p_id=searchforemployer_WAR_registrationportlet&amp;p_p_lifecycle=0&amp;p_p_state=exclusive&amp;p_p_mode=view&amp;p_p_col_id=column-1&amp;p_p_col_count=1&amp;_searchforemployer_WAR_registrationportlet_currentUrl=https%3A%2F%2Fassist2-uat.perkeso.gov.my%2Fweb%2Fregistration%2Fupdate%2Fupdate-add-supporting-document%3Fp_p_id%3Dsearchforemployer_WAR_registrationportlet%26p_p_lifecycle%3D0%26p_p_state%3Dnormal%26p_p_mode%3Dview%26p_p_col_id%3Dcolumn-1%26p_p_col_count%3D1%26_searchforemployer_WAR_registrationportlet_employerIdKey%3D10000152%26_searchforemployer_WAR_registrationportlet_mvcPath%3D%252Fapps%252Freg%252Fsupporting_document%252Fsupporting_document_form.jsp%26_searchforemployer_WAR_registrationportlet_browserIdKey%3D1536823675923%26_searchforemployer_WAR_registrationportlet_regSectionKey%3D207%26_searchforemployer_WAR_registrationportlet_regViewKey%3D61&amp;_searchforemployer_WAR_registrationportlet_mvcPath=%2Fapps%2Freg%2Fsupporting_document%2Fpopup_model%2Fsupporting_document_popup_model.jsp&amp;_searchforemployer_WAR_registrationportlet_employerIdKey=10000152&amp;_searchforemployer_WAR_registrationportlet_browserIdKey=1536823675923&amp;_searchforemployer_WAR_registrationportlet_isTemp=true&amp;_searchforemployer_WAR_registrationportlet_docSectionId=112&amp;_searchforemployer_WAR_registrationportlet_backJspPath=%2Fapps%2Freg%2Fsupporting_document%2Fsupporting_document_form.jsp&amp;_searchforemployer_WAR_registrationportlet_regViewKey=61</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-lg blueBtn col-md-2 pull-right popup-trigger</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
					ADD DOCUMENT
	             </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_searchforemployer_WAR_registrationportlet_dialogBtn&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <value>//a[@id='_searchforemployer_WAR_registrationportlet_dialogBtn']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <value>//div[@id='yui_patched_v3_11_0_1_1536823743025_315']/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <value>//a[contains(text(),'ADD DOCUMENT')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Uploaded Supporting Document(s) Listing'])[1]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Document Received Date'])[1]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No.'])[1]/preceding::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Document'])[1]/preceding::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <value>//a[contains(@href, 'https://assist2-uat.perkeso.gov.my/web/registration/update/update-add-supporting-document?p_p_id=searchforemployer_WAR_registrationportlet&amp;p_p_lifecycle=0&amp;p_p_state=exclusive&amp;p_p_mode=view&amp;p_p_col_id=column-1&amp;p_p_col_count=1&amp;_searchforemployer_WAR_registrationportlet_currentUrl=https%3A%2F%2Fassist2-uat.perkeso.gov.my%2Fweb%2Fregistration%2Fupdate%2Fupdate-add-supporting-document%3Fp_p_id%3Dsearchforemployer_WAR_registrationportlet%26p_p_lifecycle%3D0%26p_p_state%3Dnormal%26p_p_mode%3Dview%26p_p_col_id%3Dcolumn-1%26p_p_col_count%3D1%26_searchforemployer_WAR_registrationportlet_employerIdKey%3D10000152%26_searchforemployer_WAR_registrationportlet_mvcPath%3D%252Fapps%252Freg%252Fsupporting_document%252Fsupporting_document_form.jsp%26_searchforemployer_WAR_registrationportlet_browserIdKey%3D1536823675923%26_searchforemployer_WAR_registrationportlet_regSectionKey%3D207%26_searchforemployer_WAR_registrationportlet_regViewKey%3D61&amp;_searchforemployer_WAR_registrationportlet_mvcPath=%2Fapps%2Freg%2Fsupporting_document%2Fpopup_model%2Fsupporting_document_popup_model.jsp&amp;_searchforemployer_WAR_registrationportlet_employerIdKey=10000152&amp;_searchforemployer_WAR_registrationportlet_browserIdKey=1536823675923&amp;_searchforemployer_WAR_registrationportlet_isTemp=true&amp;_searchforemployer_WAR_registrationportlet_docSectionId=112&amp;_searchforemployer_WAR_registrationportlet_backJspPath=%2Fapps%2Freg%2Fsupporting_document%2Fsupporting_document_form.jsp&amp;_searchforemployer_WAR_registrationportlet_regViewKey=61')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//div/a</value>
   </webElementXpaths>
</WebElementEntity>
