<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Under enforcement</name>
   <tag></tag>
   <elementGuidId>f185a834-0881-453a-8501-1b55dec72ddf</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://assist2-uat.perkeso.gov.my/web/registration/update/update-employee-information-employer-?p_p_id=searchforemployer_WAR_registrationportlet&amp;p_p_lifecycle=0&amp;p_p_state=exclusive&amp;p_p_mode=view&amp;p_p_col_id=column-1&amp;p_p_col_count=1&amp;_searchforemployer_WAR_registrationportlet_redirect=%2Fweb%2Fregistration%2Fupdate%2Fupdate-employee-information-employer-%3Fp_auth%3DfJ0tlXoQ%26p_p_id%3Dsearchforemployer_WAR_registrationportlet%26p_p_lifecycle%3D1%26p_p_state%3Dnormal%26p_p_mode%3Dview%26p_p_col_id%3Dcolumn-1%26p_p_col_count%3D1%26_searchforemployer_WAR_registrationportlet_javax.portlet.action%3DexeAction%26_searchforemployer_WAR_registrationportlet_mvcPath%3D%252Fapps%252Freg%252Fupdate_employee_info%252Fupdate_employee_info_preview.jsp%26_searchforemployer_WAR_registrationportlet_browserIdKey%3D1535360249165&amp;_searchforemployer_WAR_registrationportlet_mvcPath=%2Fapps%2Freg%2Fcommon%2Fcommon_under_enforcement_remark_popup.jsp&amp;_searchforemployer_WAR_registrationportlet_actionResourceKey=updateEmployeeInfoSubmitId&amp;_searchforemployer_WAR_registrationportlet_passActionKey=444</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>targets</name>
      <type>Main</type>
      <value>baseMsgDivId</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>popup-trigger btn btn-lg blueBtn col-md-2 pull-right popUpBrowserIdBtn</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>yui_patched_v3_11_0_1_1535360397270_344</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Under Enforcement
					</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;yui_patched_v3_11_0_1_1535360397270_344&quot;)</value>
   </webElementProperties>
</WebElementEntity>
