<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Next in Resigned Page</name>
   <tag></tag>
   <elementGuidId>19d11fa7-5a72-484d-b035-b72565806a8c</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://assist2-uat.perkeso.gov.my/web/registration/eis-update/form-3-eis-cessation-as-employer?p_auth=ftbzuTmS&amp;p_p_id=searchforemployersip_WAR_registrationportlet&amp;p_p_lifecycle=1&amp;p_p_state=normal&amp;p_p_mode=view&amp;p_p_col_id=column-1&amp;p_p_col_count=1&amp;_searchforemployersip_WAR_registrationportlet_javax.portlet.action=exeAction&amp;_searchforemployersip_WAR_registrationportlet_regActionKey=614&amp;_searchforemployersip_WAR_registrationportlet_cmd=jspPathId&amp;_searchforemployersip_WAR_registrationportlet_browserIdKey=1536115932192</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-lg blueBtn col-md-2 pull-right browserIdBtn</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>yui_patched_v3_11_0_1_1536116015751_414</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> NEXT
					</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;yui_patched_v3_11_0_1_1536116015751_414&quot;)</value>
   </webElementProperties>
</WebElementEntity>
