<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Letter of inquiry</name>
   <tag></tag>
   <elementGuidId>40a714cf-6442-4028-8ad8-ed8e42b7571f</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://assist2-uat.perkeso.gov.my/web/registration/update/update-employee-information-employee-?p_p_id=searchforemployee_WAR_registrationportlet&amp;p_p_lifecycle=2&amp;p_p_state=normal&amp;p_p_mode=view&amp;p_p_resource_id=downloadLetterDocumentId&amp;p_p_cacheability=cacheLevelPage&amp;p_p_col_id=column-1&amp;p_p_col_count=1&amp;_searchforemployee_WAR_registrationportlet_docFileId=15703086&amp;_searchforemployee_WAR_registrationportlet_browserIdKey=1536045352811&amp;_searchforemployee_WAR_registrationportlet_jspPage=%2Fapps%2Freg%2Fcommon%2Fcommon_update_case_success.jsp&amp;_searchforemployee_WAR_registrationportlet_regViewKey=107</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>iconDownload</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btndownload</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
							 
							Letter of inquiry.pdf
						</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;iconDownload&quot;)</value>
   </webElementProperties>
</WebElementEntity>
