<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Add Employee Button</name>
   <tag></tag>
   <elementGuidId>2d72add8-9f31-4f66-9e72-c7594a6dbc75</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addNewBtnPopBtnId</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formid</name>
      <type>Main</type>
      <value>_searchforemployer_WAR_registrationportlet_outerForm</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>popup-trigger 
					btn btn-lg blueBtn col-md-2 pull-right browserIdBtn</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://assist2-uat.perkeso.gov.my/web/registration/update/update-add-new-employee?p_p_id=searchforemployer_WAR_registrationportlet&amp;p_p_lifecycle=0&amp;p_p_state=exclusive&amp;p_p_mode=view&amp;p_p_col_id=column-1&amp;p_p_col_count=1&amp;_searchforemployer_WAR_registrationportlet_currentUrl=https%3A%2F%2Fassist2-uat.perkeso.gov.my%2Fweb%2Fregistration%2Fupdate%2Fupdate-add-new-employee%3Fp_p_id%3Dsearchforemployer_WAR_registrationportlet%26p_p_lifecycle%3D0%26p_p_state%3Dnormal%26p_p_mode%3Dview%26p_p_col_id%3Dcolumn-1%26p_p_col_count%3D1%26_searchforemployer_WAR_registrationportlet_employerIdKey%3D10068888%26_searchforemployer_WAR_registrationportlet_mvcPath%3D%252Fapps%252Freg%252Fupdate_add_new_employee%252Fupdate_add_new_employee_form.jsp%26_searchforemployer_WAR_registrationportlet_browserIdKey%3D1535956543839%26_searchforemployer_WAR_registrationportlet_regSectionKey%3D201%26_searchforemployer_WAR_registrationportlet_regViewKey%3D150&amp;_searchforemployer_WAR_registrationportlet_mvcPath=%2Fapps%2Freg%2Fcommon%2Fcommon_employee_info_popup_form.jsp&amp;_searchforemployer_WAR_registrationportlet_employerIdKey=10068888&amp;_searchforemployer_WAR_registrationportlet_actionResourceKey=updateAddNewEmployeeId&amp;_searchforemployer_WAR_registrationportlet_popUpAction=add&amp;_searchforemployer_WAR_registrationportlet_regSectionKey=201&amp;_searchforemployer_WAR_registrationportlet_browserIdKey=1535956543839</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
					ADD EMPLOYEE
				</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addNewBtnPopBtnId&quot;)</value>
   </webElementProperties>
</WebElementEntity>
