<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Add Document for Pending Case</name>
   <tag></tag>
   <elementGuidId>b5b019e5-c331-40e8-a358-41fca1accc03</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[@id = '_searchforemployer_WAR_registrationportlet_dialogBtn' and (contains(text(), 'ADD DOCUMENT') or contains(., 'ADD DOCUMENT'))]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_searchforemployer_WAR_registrationportlet_dialogBtn</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formid</name>
      <type>Main</type>
      <value>_newreg_WAR_registrationportlet_saveNContinueFormId</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://assist2-uat.perkeso.gov.my/web/registration/registration?p_p_id=newreg_WAR_registrationportlet&amp;p_p_lifecycle=0&amp;p_p_state=exclusive&amp;p_p_mode=view&amp;p_p_col_id=column-1&amp;p_p_col_count=1&amp;_newreg_WAR_registrationportlet_currentUrl=https%3A%2F%2Fassist2-uat.perkeso.gov.my%2Fweb%2Fregistration%2Fregistration%3Fp_p_id%3Dnewreg_WAR_registrationportlet%26p_p_lifecycle%3D0%26p_p_state%3Dnormal%26p_p_mode%3Dview%26p_p_col_id%3Dcolumn-1%26p_p_col_count%3D1%26_newreg_WAR_registrationportlet_browserIdKey%3D1535436296966%26_newreg_WAR_registrationportlet_jspPage%3D%252Fapps%252Freg%252Fcommon%252Fcommon_supporting_doc_form.jsp%26_newreg_WAR_registrationportlet_regViewKey%3D17&amp;_newreg_WAR_registrationportlet_mvcPath=%2Fapps%2Freg%2Fsupporting_document%2Fpopup_model%2Fsupporting_document_popup_model.jsp&amp;_newreg_WAR_registrationportlet_browserIdKey=1535436296966&amp;_newreg_WAR_registrationportlet_isTemp=true&amp;_newreg_WAR_registrationportlet_docSectionId=100&amp;_newreg_WAR_registrationportlet_backJspPath=%2Fapps%2Freg%2Fnew_reg%2Fnew_reg_eligible_employee.jsp&amp;_newreg_WAR_registrationportlet_regViewKey=17</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-lg blueBtn col-md-2 pull-right popup-trigger</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ADD DOCUMENT</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_newreg_WAR_registrationportlet_dialogBtn&quot;)</value>
   </webElementProperties>
</WebElementEntity>
