<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Save Button for Add Employee</name>
   <tag></tag>
   <elementGuidId>d431671f-5086-4780-bdb3-a3602eb5ce67</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//a[@targets = 'baseMsgDivId' and (@class = 'btn btn-lg blueBtn col-md-2 pull-right browserIdBtn' or @class = 'btn btn-lg blueBtn col-md-2 pull-right browserIdBtn katalonHighlight' or @class = 'btn btn-lg blueBtn col-md-2 pull-right browserIdBtn katalonDeHighlight')and (contains(text(), 'SAVE') or contains(., 'SAVE'))])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formid</name>
      <type>Main</type>
      <value>_newreg_WAR_registrationportlet_employeeForm</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://assist2-uat.perkeso.gov.my/web/registration/registration?p_auth=4znGW1BU&amp;p_p_id=newreg_WAR_registrationportlet&amp;p_p_lifecycle=1&amp;p_p_state=normal&amp;p_p_mode=view&amp;_newreg_WAR_registrationportlet_redirect=https%3A%2F%2Fassist2-uat.perkeso.gov.my%2Fweb%2Fregistration%2Fregistration%3Fp_p_id%3Dnewreg_WAR_registrationportlet%26p_p_lifecycle%3D0%26p_p_state%3Dnormal%26p_p_mode%3Dview%26p_p_col_id%3Dcolumn-1%26p_p_col_count%3D1%26_newreg_WAR_registrationportlet_browserIdKey%3D1534322786413%26_newreg_WAR_registrationportlet_jspPage%3D%2Fapps%2Freg%2Fnew_reg%2Fnew_reg_form2.jsp%26_newreg_WAR_registrationportlet_regViewKey%3D12&amp;_newreg_WAR_registrationportlet_newRegTempEmployeeTableorderByType=asc&amp;_newreg_WAR_registrationportlet_javax.portlet.action=exeAction&amp;_newreg_WAR_registrationportlet_regActionKey=10&amp;_newreg_WAR_registrationportlet_mvcPath=%2Fapps%2Freg%2Fnew_reg%2Fnew_reg_form2.jsp&amp;_newreg_WAR_registrationportlet_browserIdKey=1534322786413&amp;_newreg_WAR_registrationportlet_newRegTempEmployeeTable=1&amp;_newreg_WAR_registrationportlet_cmd=employeeRegistrationFormId&amp;_newreg_WAR_registrationportlet_popUpAction=add&amp;_newreg_WAR_registrationportlet_deltanewRegTempEmployeeTable=10&amp;_newreg_WAR_registrationportlet_regViewKey=12</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>targets</name>
      <type>Main</type>
      <value>baseMsgDivId</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-lg blueBtn col-md-2 pull-right</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>yui_patched_v3_11_0_1_1534322864955_561</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>contains</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SAVE</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//a[@targets = 'baseMsgDivId' and (@class = 'btn btn-lg blueBtn col-md-2 pull-right browserIdBtn' or @class = 'btn btn-lg blueBtn col-md-2 pull-right browserIdBtn katalonHighlight' or @class = 'btn btn-lg blueBtn col-md-2 pull-right browserIdBtn katalonDeHighlight')and (contains(text(), 'SAVE') or contains(., 'SAVE'))])[2]</value>
   </webElementProperties>
</WebElementEntity>
