<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Submit Button at Preview Screen of RO</name>
   <tag></tag>
   <elementGuidId>a349c77c-6339-465e-942e-417a4b1bede3</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>popupvalidatesubmit</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-confirmation-title</name>
      <type>Main</type>
      <value>Confirmation</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-confirmation-content</name>
      <type>Main</type>
      <value>Proceed for Submission?</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formid</name>
      <type>Main</type>
      <value>_newreg_WAR_registrationportlet_fm</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);&amp;_newreg_WAR_registrationportlet_browserIdKey=1535440456603</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>url</name>
      <type>Main</type>
      <value>https://assist2-uat.perkeso.gov.my/web/registration/registration?p_auth=rK8nfDKA&amp;p_p_id=newreg_WAR_registrationportlet&amp;p_p_lifecycle=1&amp;p_p_state=normal&amp;p_p_mode=view&amp;p_p_col_id=column-1&amp;p_p_col_count=1&amp;_newreg_WAR_registrationportlet_javax.portlet.action=exeAction&amp;_newreg_WAR_registrationportlet_regActionKey=990&amp;_newreg_WAR_registrationportlet_cmd=newRegSubmitId&amp;_newreg_WAR_registrationportlet_browserIdKey=1535440456603&amp;_newreg_WAR_registrationportlet_processInstanceIdKey=&amp;_newreg_WAR_registrationportlet_regViewKey=14&amp;_newreg_WAR_registrationportlet_mvcPath=%2Fapps%2Freg%2Fnew_reg%2Fnew_reg_preview.jsp</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-lg blueBtn col-md-2 pull-right browserIdBtn</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>yui_patched_v3_11_0_1_1535440501092_349</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> SUBMIT
					</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;yui_patched_v3_11_0_1_1535440501092_349&quot;)</value>
   </webElementProperties>
</WebElementEntity>
