<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Underenforcement</name>
   <tag></tag>
   <elementGuidId>a7bac2fa-cb1e-4ee2-9a7b-e50c1d5318dc</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://assist2-uat.perkeso.gov.my/web/registration/eis-update/form-3-eis-cessation-as-employer?p_p_id=searchforemployersip_WAR_registrationportlet&amp;p_p_lifecycle=0&amp;p_p_state=exclusive&amp;p_p_mode=view&amp;p_p_col_id=column-1&amp;p_p_col_count=1&amp;_searchforemployersip_WAR_registrationportlet_redirect=%2Fweb%2Fregistration%2Feis-update%2Fform-3-eis-cessation-as-employer%3Fp_auth%3D7yIcmDg7%26p_p_id%3Dsearchforemployersip_WAR_registrationportlet%26p_p_lifecycle%3D1%26p_p_state%3Dnormal%26p_p_mode%3Dview%26p_p_col_id%3Dcolumn-1%26p_p_col_count%3D1%26_searchforemployersip_WAR_registrationportlet_javax.portlet.action%3DexeAction%26_searchforemployersip_WAR_registrationportlet_mvcPath%3D%252Fapps%252Freg%252Fdiscontinue_business_sip%252Fdiscontinue_business_sip_preview.jsp%26_searchforemployersip_WAR_registrationportlet_browserIdKey%3D1536114008568&amp;_searchforemployersip_WAR_registrationportlet_mvcPath=%2Fapps%2Freg%2Fcommon%2Fcommon_under_enforcement_remark_popup.jsp&amp;_searchforemployersip_WAR_registrationportlet_actionResourceKey=discontinueBusinessSipEmployerInfoSubmitId&amp;_searchforemployersip_WAR_registrationportlet_passActionKey=612&amp;_searchforemployersip_WAR_registrationportlet_browserIdKey=1536114008568</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>targets</name>
      <type>Main</type>
      <value>baseMsgDivId</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>popup-trigger btn btn-lg blueBtn col-md-2 m-t-20 pull-right btnUnderEnforment browserIdBtn</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>yui_patched_v3_11_0_1_1536114159739_377</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
								Under Enforcement
							</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;yui_patched_v3_11_0_1_1536114159739_377&quot;)</value>
   </webElementProperties>
</WebElementEntity>
