<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Add Document</name>
   <tag></tag>
   <elementGuidId>61c3c2b1-45f6-473f-8a32-a81b2865b77c</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://assist2-uat.perkeso.gov.my/web/registration/request-ssn?p_auth=Q9pr87b4&amp;p_p_id=ssn_WAR_registrationportlet&amp;p_p_lifecycle=1&amp;p_p_state=exclusive&amp;p_p_mode=view&amp;_ssn_WAR_registrationportlet_redirect=https%3A%2F%2Fassist2-uat.perkeso.gov.my%2Fweb%2Fregistration%2Frequest-ssn%3Fp_p_id%3Dssn_WAR_registrationportlet%26p_p_lifecycle%3D0%26p_p_state%3Dnormal%26p_p_mode%3Dview%26p_p_col_id%3Dcolumn-1%26p_p_col_count%3D1%26_ssn_WAR_registrationportlet_browserIdKey%3D1535091787228%26_ssn_WAR_registrationportlet_jspPage%3D%2Fapps%2Freg%2Fcommon%2Fcommon_supporting_doc_form.jsp%26_ssn_WAR_registrationportlet_refCaseNo%3DSSN08201800001011%26_ssn_WAR_registrationportlet_regViewKey%3D54%26_ssn_WAR_registrationportlet_tempSsnIdKey%3D2482&amp;_ssn_WAR_registrationportlet_javax.portlet.action=exeAction&amp;_ssn_WAR_registrationportlet_mvcPath=%2Fapps%2Freg%2Fcommon%2Fcommon_supporting_doc_form.jsp&amp;_ssn_WAR_registrationportlet_browserIdKey=1535091787228&amp;_ssn_WAR_registrationportlet_cmd=saveSuppDocFileId&amp;_ssn_WAR_registrationportlet_regViewKey=54</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-lg blueBtn col-md-2 pull-right</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formid</name>
      <type>Main</type>
      <value>_ssn_WAR_registrationportlet_uploadDocForm</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>targets</name>
      <type>Main</type>
      <value>baseMsgDivId</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>yui_patched_v3_11_0_1_1535091875622_456</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
										ADD DOCUMENT
								     </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;yui_patched_v3_11_0_1_1535091875622_456&quot;)</value>
   </webElementProperties>
</WebElementEntity>
