<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Letter of acknowledgement</name>
   <tag></tag>
   <elementGuidId>240f10f7-a2ba-4a99-b96e-cd632fb9766a</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://assist2-uat.perkeso.gov.my/web/registration/request-ssn?p_p_id=ssn_WAR_registrationportlet&amp;p_p_lifecycle=2&amp;p_p_state=normal&amp;p_p_mode=view&amp;p_p_resource_id=downloadLetterDocumentId&amp;p_p_cacheability=cacheLevelPage&amp;p_p_col_id=column-1&amp;p_p_col_count=1&amp;_ssn_WAR_registrationportlet_docFileId=15702470&amp;_ssn_WAR_registrationportlet_routedToRoleIdKey=RIO&amp;_ssn_WAR_registrationportlet_browserIdKey=1535423307895&amp;_ssn_WAR_registrationportlet_jspPage=%2Fapps%2Freg%2Fssn%2Fssn_success.jsp&amp;_ssn_WAR_registrationportlet_regViewKey=53</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>iconDownload</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btndownload</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
									 
									Letter of acknowledgement.pdf
								</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;iconDownload&quot;)</value>
   </webElementProperties>
</WebElementEntity>
