<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Submit</name>
   <tag></tag>
   <elementGuidId>715061c4-1e98-47ec-a5e0-439591b188ff</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>popupvalidatesubmit</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://assist2-uat.perkeso.gov.my/web/registration/eis-update/form-3-eis-cessation-as-employer?p_auth=NJ9POX5Z&amp;p_p_id=searchforemployersip_WAR_registrationportlet&amp;p_p_lifecycle=1&amp;p_p_state=normal&amp;p_p_mode=view&amp;p_p_col_id=column-1&amp;p_p_col_count=1&amp;_searchforemployersip_WAR_registrationportlet_javax.portlet.action=exeAction&amp;_searchforemployersip_WAR_registrationportlet_regActionKey=608&amp;_searchforemployersip_WAR_registrationportlet_cmd=discontinueBusinessSipEmployerInfoSubmitId&amp;_searchforemployersip_WAR_registrationportlet_browserIdKey=1536029169437&amp;_searchforemployersip_WAR_registrationportlet_processInstanceIdKey=&amp;_searchforemployersip_WAR_registrationportlet_regViewKey=88&amp;_searchforemployersip_WAR_registrationportlet_mvcPath=%2Fapps%2Freg%2Fdiscontinue_business_sip%2Fdiscontinue_business_sip_preview.jsp</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>url</name>
      <type>Main</type>
      <value>https://assist2-uat.perkeso.gov.my/web/registration/eis-update/form-3-eis-cessation-as-employer?p_auth=NJ9POX5Z&amp;p_p_id=searchforemployersip_WAR_registrationportlet&amp;p_p_lifecycle=1&amp;p_p_state=normal&amp;p_p_mode=view&amp;p_p_col_id=column-1&amp;p_p_col_count=1&amp;_searchforemployersip_WAR_registrationportlet_javax.portlet.action=exeAction&amp;_searchforemployersip_WAR_registrationportlet_regActionKey=608&amp;_searchforemployersip_WAR_registrationportlet_cmd=discontinueBusinessSipEmployerInfoSubmitId&amp;_searchforemployersip_WAR_registrationportlet_browserIdKey=1536029169437&amp;_searchforemployersip_WAR_registrationportlet_processInstanceIdKey=&amp;_searchforemployersip_WAR_registrationportlet_regViewKey=88&amp;_searchforemployersip_WAR_registrationportlet_mvcPath=%2Fapps%2Freg%2Fdiscontinue_business_sip%2Fdiscontinue_business_sip_preview.jsp</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-confirmation-title</name>
      <type>Main</type>
      <value>Confirmation</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-confirmation-content</name>
      <type>Main</type>
      <value>Proceed for Submission?</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formid</name>
      <type>Main</type>
      <value>_searchforemployersip_WAR_registrationportlet_fm</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnSubmitId</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn blueBtn col-md-2 m-t-20 btn-lg pull-right btnSubmit popUpBrowserIdBtn</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
							SUBMIT
		            	</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnSubmitId&quot;)</value>
   </webElementProperties>
</WebElementEntity>
