<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Add Document</name>
   <tag></tag>
   <elementGuidId>5909a61b-ab46-4bbd-9956-1799e1b5fae8</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_searchforemployer_WAR_registrationportlet_dialogBtn</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formid</name>
      <type>Main</type>
      <value>_searchforemployer_WAR_registrationportlet_saveNContinueFormId</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://assist2-uat.perkeso.gov.my/web/registration/update/form-1a-cessation-as-employer-discontinue-business-?p_p_id=searchforemployer_WAR_registrationportlet&amp;p_p_lifecycle=0&amp;p_p_state=exclusive&amp;p_p_mode=view&amp;p_p_col_id=column-1&amp;p_p_col_count=1&amp;_searchforemployer_WAR_registrationportlet_currentUrl=https%3A%2F%2Fassist2-uat.perkeso.gov.my%2Fweb%2Fregistration%2Fupdate%2Fform-1a-cessation-as-employer-discontinue-business-%3Fp_p_id%3Dsearchforemployer_WAR_registrationportlet%26p_p_lifecycle%3D0%26p_p_state%3Dnormal%26p_p_mode%3Dview%26p_p_col_id%3Dcolumn-1%26p_p_col_count%3D1%26_searchforemployer_WAR_registrationportlet_browserIdKey%3D1535953392971%26_searchforemployer_WAR_registrationportlet_jspPage%3D%252Fapps%252Freg%252Fcommon%252Fcommon_supporting_doc_form.jsp%26_searchforemployer_WAR_registrationportlet_regViewKey%3D84&amp;_searchforemployer_WAR_registrationportlet_mvcPath=%2Fapps%2Freg%2Fsupporting_document%2Fpopup_model%2Fsupporting_document_popup_model.jsp&amp;_searchforemployer_WAR_registrationportlet_browserIdKey=1535953392971&amp;_searchforemployer_WAR_registrationportlet_isTemp=true&amp;_searchforemployer_WAR_registrationportlet_docSectionId=109&amp;_searchforemployer_WAR_registrationportlet_backJspPath=%2Fapps%2Freg%2Fupdate_employee_resigned_date%2Fupdate_employee_resigned_date_form.jsp&amp;_searchforemployer_WAR_registrationportlet_regViewKey=84</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-lg blueBtn col-md-2 pull-right popup-trigger</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
					ADD DOCUMENT
	             </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_searchforemployer_WAR_registrationportlet_dialogBtn&quot;)</value>
   </webElementProperties>
</WebElementEntity>
